name: DesigniteJava code quality

on:
  workflow_call:
    secrets:
      PAT:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: DesigniteJava_action
        uses: DesigniteTools/DJAction@v2.0.0
        with:
          PAT: ${{ secrets.PAT }}