name: Static Analysis
on:
  pull_request:
  push:
  workflow_call:

jobs:
  check_spotless:
    uses: ./.github/workflows/reusable_spotless_check.yml
    permissions:
      contents: read
  check_pmd:
    uses: ./.github/workflows/reusable_spotless_check.yml
    permissions:
      contents: read